name: CI/CD Pipeline

on:
  push:
    branches: [main, uat]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # DEPLOY TO PRODUCTION
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: 80.225.208.24
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/TRIP_Planner
            git checkout main
            git pull origin main
            cd backend
            pip3 install -r requirements.txt 2>/dev/null || true
            bash restart_backend.sh
            cd ../frontend
            npm install && npm run build
            sudo chmod -R 755 dist/

      # DEPLOY TO UAT
      - name: Deploy UAT
        if: github.ref == 'refs/heads/uat'
        uses: appleboy/ssh-action@v1
        with:
          host: 80.225.208.24
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/TRIP_Planner_UAT
            git checkout uat
            git pull origin uat
            cd backend
            pip3 install -r requirements.txt 2>/dev/null || true
            bash restart_backend.sh
            cd ../frontend
            npm install && npm run build
            sudo chmod -R 755 dist/
